name: Keepalive empty commit

on:
  schedule:
    - cron: "0 */10 * * *"    # every 10 hours, at minute 0 (UTC)
  workflow_dispatch:          # allow manual runs from the UI

permissions:
  contents: write             # GITHUB_TOKEN can push

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: main            # change if your default branch isn't 'main'

      - name: Make empty commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keepalive $(date -u +%FT%TZ)"
          git push
